# Generated by Django 4.1 on 2025-04-09 21:01

from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ("octofit", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="members",
            field=djongo.models.fields.JSONField(),
        ),
    ]
